#!/usr/bin/env node
/**
 * Emit src/environments/environment.prod.ts from build-time env vars so
 * Vercel / any host can inject the backend URL + API key without a code edit.
 *
 *   LEGAL_RAG_API_URL   e.g. https://<space>.hf.space
 *   LEGAL_RAG_API_KEY   the same value set on the backend Space
 */
const fs = require('node:fs');
const path = require('node:path');

const apiUrl = process.env.LEGAL_RAG_API_URL || '/api';
const apiKey = process.env.LEGAL_RAG_API_KEY || '';

const contents = `// AUTO-GENERATED by scripts/set-env.js at build time. Do not edit.
export const environment = {
  production: true,
  apiUrl: ${JSON.stringify(apiUrl)},
  apiKey: ${JSON.stringify(apiKey)},
};
`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.writeFileSync(outPath, contents, 'utf8');
console.log(`[set-env] wrote ${outPath}`);
console.log(`[set-env]   apiUrl = ${apiUrl}`);
console.log(`[set-env]   apiKey = ${apiKey ? '(set)' : '(empty)'}`);
